name = "wiki"

compatibility_date = "2025-08-09"
compatibility_flags = [ "nodejs_compat" ]

[assets]
directory = "./dist"
not_found_handling = "404-page"

[observability.logs]
enabled = true

[vars]
BUN_VERSION = "1.2.20"
SKIP_DEPENDENCY_INSTALL = "true"
